apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-delete
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-delete
  template:
    metadata:
      labels:
        app: todo-delete
    spec:
      containers:
      - name: todo-delete
        image: acrrg3.azurecr.io/todo-delete-tasks-api:v1
        ports:
        - containerPort: 80
